{% set name = "deepmd-kit" %}
{% set version = "1.3.3" %}
{% set lammpsversion = "stable_29Oct2020" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/deepmodeling/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 5fbad41743462a152b01e07e0c1c5db33dbaaad0fde20d599b771185d0730dfb
    patches:
      - revert_find_protobuf.patch
      - only_link_what_you_use_on_gnu.patch
      - win.patch  # [win]
      - osx.patch  # [osx]
  - url: https://github.com/lammps/lammps/archive/{{ lammpsversion }}.tar.gz
    sha256: 759705e16c1fedd6aa6e07d028cc0c78d73c76b76736668420946a74050c3726
    folder: lammps
    patches:
      - deepmd.patch
  - url: https://github.com/abseil/abseil-cpp/archive/df3ea785d8c30a9503321a3d35ee7d35808f190d.tar.gz
    sha256: f368a8476f4e2e0eccf8a7318b98dafbe30b2600f4e3cf52636e5eb145aba06a
    folder: absl
    patches:
      - com_google_absl_fix_mac_and_nvcc_build.patch

build:
  number: 0
  skip: true  # [win]
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.7
    - make  # [unix]
    - ninja
    - rsync

  host:
    - python
    - pip
    - scikit-build
    - m2r
    - tensorflow
    - libtensorflow_cc  # [linux]
    - setuptools_scm
    - numpy >=1.16
    - scipy
    - dargs
    - pyyaml
    - mpich  # [linux]
    - zlib  # [linux]
    - fftw  # [linux]
    - libpng  # [linux]

  run:
    - python
    - {{ pin_compatible('tensorflow', max_pin='x.x') }}
    - {{ pin_compatible('libtensorflow_cc', max_pin='x.x') }}  # [linux]
    - numpy
    - scipy
    - dargs
    - pyyaml
    - mpich  # [linux]

test:
  files:
    - water_se_a.json
  source_files:
    - examples/water/data
    - examples/water/lmp/water.lmp  # [linux]
    - examples/water/lmp/in.lammps  # [linux]
  imports:
    # dlopen: cannot load any more object with static TLS
    # because tensorflow link too many libraries
    # but it can successfully run on my machine
    - deepmd  # [not linux]
  commands:
    - dp -h  # [not linux]
    - dp train -h  # [not linux]
    - dp freeze -h  # [not linux]
    - dp test -h  # [not linux]
    - lmp -help  # [linux]
    - mv examples/water/data .
    #- mv examples/water/lmp/water.lmp .  # [linux]
    #- mv examples/water/lmp/in.lammps .  # [linux]
    - dp train water_se_a.json  # [not linux]
    - dp freeze  # [not linux]
    #- lmp -in in.lammps  # [linux]

about:
  home: https://github.com/deepmodeling/deepmd-kit
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: A deep learning package for many-body potential energy representation and molecular dynamics
  doc_url: https://github.com/deepmodeling/deepmd-kit
  dev_url: https://github.com/deepmodeling/deepmd-kit

extra:
  recipe-maintainers:
    - njzjz
