{% set name = "deepmd-kit" %}
{% set version = "1.2.4" %}
{% set lammpsversion = "stable_29Oct2020" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/deepmodeling/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 8863f3e5cbc2fbb8e5a75c7f38cfcdaf1dae274af77c7a65a92a9f0f1eace689
    patches:
      - revert_find_protobuf.patch
      - win.patch  # [win]
      - osx.patch  # [osx]
  - url: https://github.com/lammps/lammps/archive/{{ lammpsversion }}.tar.gz
    sha256: 759705e16c1fedd6aa6e07d028cc0c78d73c76b76736668420946a74050c3726
    folder: lammps
    patches:
      - deepmd.patch

build:
  number: 0
  skip: true  # [win]
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.7
    - make  # [unix]
    - ninja

  host:
    - python
    - pip
    - scikit-build
    - m2r
    - tensorflow
    - libtensorflow_cc  # [linux]
    - setuptools_scm
    - numpy >=1.16
    - scipy
    - mpich  # [linux]
    - zlib  # [linux]
    - fftw  # [linux]
    - libpng  # [linux]

  run:
    - python
    - {{ pin_compatible('tensorflow', max_pin='x.x') }}
    - {{ pin_compatible('libtensorflow_cc', max_pin='x.x') }}  # [linux]
    - numpy
    - scipy
    - mpich  # [linux]

test:
  files:
    - water_se_a.json
  source_files:
    - examples/water/data
    - examples/water/lmp/water.lmp  # [linux]
    - examples/water/lmp/in.lammps  # [linux]
  imports:
    - deepmd
  commands:
    - dp -h
    - dp train -h
    - dp freeze -h
    - dp test -h
    - lmp -help  # [linux]
    - mv examples/water/data .
    - mv examples/water/lmp/water.lmp .  # [linux]
    - mv examples/water/lmp/in.lammps .  # [linux]
    - dp train water_se_a.json
    - dp freeze
    - lmp -in in.lammps  # [linux]

about:
  home: https://github.com/deepmodeling/deepmd-kit
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: A deep learning package for many-body potential energy representation and molecular dynamics
  doc_url: https://github.com/deepmodeling/deepmd-kit
  dev_url: https://github.com/deepmodeling/deepmd-kit

extra:
  recipe-maintainers:
    - njzjz
