{% set name = "deepmd-kit" %}
{% set version = "1.1.0" %}
{% set lammpsversion = "stable_7Aug2019" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/deepmodeling/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: faaeca5b446ae04f7303e23d3d438bd42103536d1332d7e9492aaedd767ac006
    patches:
      - win.patch  # [win]
      - osx.patch  # [osx]
  - url: https://github.com/lammps/lammps/archive/{{ lammpsversion }}.tar.gz
    sha256: 5380c1689a93d7922e3d65d9c186401d429878bb3cbe9a692580d3470d6a253f
    folder: lammps
    patches:
      - deepmd.patch

build:
  number: 0
  skip: true  # [win]	

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.7
    - make  # [unix]
    - ninja

  host:
    - python >=3.6
    - pip
    - scikit-build
    - m2r
    - tensorflow
    - libtensorflow_cc  # [linux]
    - setuptools_scm
    - numpy
    - scipy
    - mpich  # [linux]
    - zlib  # [linux]
    - fftw  # [linux]
    - libpng  # [linux]

  run:
    - python
    - tensorflow
    - libtensorflow_cc  # [linux]
    - numpy
    - scipy
    - mpich  # [linux]
    - fftw  # [linux]

test:
  files:
    - water_se_a.json
  source_files:
    - examples/water/data
    - examples/water/lmp/water.lmp  # [linux]
    - examples/water/lmp/in.lammps  # [linux]
  imports:
    - deepmd
  commands:
    - dp -h
    - dp train -h
    - dp freeze -h
    - dp test -h
    - lmp -help  # [linux]
    - mv examples/water/data .
    - mv examples/water/lmp/water.lmp .  # [linux]
    - mv examples/water/lmp/in.lammps .  # [linux]
    - dp train water_se_a.json
    - dp freeze
    - lmp -in in.lammps  # [linux]

about:
  home: https://github.com/deepmodeling/deepmd-kit
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'A deep learning package for many-body potential energy representation and molecular dynamics'
  doc_url: https://github.com/deepmodeling/deepmd-kit
  dev_url: https://github.com/deepmodeling/deepmd-kit

extra:
  recipe-maintainers:
    - njzjz
