{% set name = "deepmd-kit" %}
{% set version = "2.2.7" %}
{% set lammps_version = "stable_2Aug2023" %}
{% set lammps_date = datetime.datetime.strptime(lammps_version.split('_')[1], "%d%b%Y") %}
{% set lammps_conda_version = "{:%Y.%m.%d}".format(lammps_date) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/deepmodeling/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 25be126de336630493732b09d3b779b89cc916345b22dfb869cc4f3a3ba6dcde
  - url: https://github.com/lammps/lammps/archive/{{ lammps_version }}.tar.gz
    sha256: 48dc8b0b0583689e80ea2052275acbc3e3fce89707ac557e120db5564257f7df
    folder: lammps

build:
  number: 1
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  skip: true  # [win]
  skip: true  # [cuda_compiler_version in ("10.2", "11.0", "11.1")]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - cmake >=3.7
    - make  # [unix]
    - ninja
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]

  host:
    - python
    - pip
    - scikit-build-core
    - hatch-fancy-pypi-readme
    - tensorflow
    - setuptools_scm
    - {{ mpi }}
    - cub  # [cuda_compiler_version == '10.2']

  run:
    - python
    - tensorflow
    - numpy
    - scipy
    - dargs >=0.3.5
    - pyyaml
    - {{ mpi }}
    - python-hostlist >=1.21
    - h5py
    - wcmatch
    - packaging

  run_constrained:
    - lammps {{ lammps_conda_version }}

test:
  files:
    - water_se_a.json
    - water.lmp
    - in.lammps
  source_files:
    - examples/water/data
  imports:
    - deepmd
  requires:
    - pip
    - lammps
  commands:
    - pip check
    - dp -h
    - dp train -h
    - dp freeze -h
    - dp test -h
    - mv examples/water/data/data_0 ./data
    - dp train water_se_a.json
    - dp freeze -o frozen_model.pb
    - mpiexec -n 1 lmp_mpi -in in.lammps  # [mpi == 'mpich']

about:
  home: https://github.com/deepmodeling/deepmd-kit
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: A deep learning package for many-body potential energy representation and molecular dynamics
  doc_url: https://github.com/deepmodeling/deepmd-kit
  dev_url: https://github.com/deepmodeling/deepmd-kit

extra:
  recipe-maintainers:
    - njzjz
