{% set name = "deepmd-kit" %}
{% set version = "2.1.1" %}
{% set lammpsversion = "stable_29Sep2021" %}
{% set tf_version = "2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/deepmodeling/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 86cfd098ad26a6c236ec695d02999b5f5574b0e8c404eb0068470991349adfc6
    patches:
      - 0001-disable-remapper.patch  # [osx]
      - 0002-avoid-static-CUDA-linking.patch
      - win.patch  # [win]
  - url: https://github.com/lammps/lammps/archive/{{ lammpsversion }}.tar.gz
    sha256: 2dff656cb21fd9a6d46c818741c99d400cfb1b12102604844663b655fb2f893d
    folder: lammps

build:
  number: 3
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - cmake >=3.7
    - make  # [unix]
    - ninja

  host:
    - python
    - pip
    - scikit-build
    - m2r
    - tensorflow {{ tf_version }}.*  # [not linux]
    - tensorflow {{ tf_version }}.* cuda{{ cuda_compiler_version | replace('.', '') }}*  # [linux and cuda_compiler_version != "None"]
    - tensorflow {{ tf_version }}.* cpu_*  # [linux and cuda_compiler_version == "None"]
    - libtensorflow_cc {{ tf_version }}.* cuda{{ cuda_compiler_version | replace('.', '') }}*  # [linux and cuda_compiler_version != "None"]
    - libtensorflow_cc {{ tf_version }}.* cpu_*  # [linux and cuda_compiler_version == "None"]
    - setuptools_scm
    - numpy 1.20.*  # [py<310]
    - numpy 1.21.*  # [py>=310]
    - scipy
    - dargs >=0.2.6
    - pyyaml
    - {{ mpi }}  # [linux]
    - python-hostlist >=1.21
    - h5py
    - wcmatch
    - cub  # [cuda_compiler_version == '10.2']
    - packaging

  run:
    - python
    - tensorflow {{ tf_version }}.*  # [not linux]
    - tensorflow {{ tf_version }}.* cuda{{ cuda_compiler_version | replace('.', '') }}*  # [linux and cuda_compiler_version != "None"]
    - tensorflow {{ tf_version }}.* cpu_*  # [linux and cuda_compiler_version == "None"]
    - libtensorflow_cc {{ tf_version }}.* cuda{{ cuda_compiler_version | replace('.', '') }}*  # [linux and cuda_compiler_version != "None"]
    - libtensorflow_cc {{ tf_version }}.* cpu_*  # [linux and cuda_compiler_version == "None"]
    - numpy 1.20.*  # [py<310]
    - numpy 1.21.*  # [py>=310]
    - scipy
    - dargs >=0.2.6
    - pyyaml
    - {{ mpi }}  # [linux]
    - python-hostlist >=1.21
    - h5py
    - wcmatch
    - packaging

  run_constrained:
    - lammps 2021.09.29  # [linux]

test:
  files:
    - water_se_a.json
  source_files:
    - examples/water/data
  imports:
    - deepmd
  requires:
    - pip
  commands:
    - pip check
    - dp -h
    - dp train -h
    - dp freeze -h
    - dp test -h

about:
  home: https://github.com/deepmodeling/deepmd-kit
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: A deep learning package for many-body potential energy representation and molecular dynamics
  doc_url: https://github.com/deepmodeling/deepmd-kit
  dev_url: https://github.com/deepmodeling/deepmd-kit

extra:
  recipe-maintainers:
    - njzjz
