{% set name = "deepmd-kit" %}
{% set version = "2.0.3" %}
{% set lammpsversion = "stable_29Sep2021" %}
{% set tf_version = "2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/deepmodeling/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 181dbf67b6c6beaf2748bda8d82c219ce6080f852b9a941387f8bbdd7552efae
    patches:
      - win.patch  # [win]
  - url: https://github.com/lammps/lammps/archive/{{ lammpsversion }}.tar.gz
    sha256: 2dff656cb21fd9a6d46c818741c99d400cfb1b12102604844663b655fb2f893d
    folder: lammps

build:
  number: 0
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - cmake >=3.7
    - make  # [unix]
    - ninja

  host:
    - python
    - pip
    - scikit-build
    - m2r
    - tensorflow {{ tf_version }}.* cuda{{ cuda_compiler_version | replace('.', '') }}*  # [cuda_compiler_version != "None"]
    - tensorflow {{ tf_version }}.* cpu_*  # [cuda_compiler_version == "None"]
    - libtensorflow_cc {{ tf_version }}.* cuda{{ cuda_compiler_version | replace('.', '') }}*  # [linux and cuda_compiler_version != "None"]
    - libtensorflow_cc {{ tf_version }}.* cpu_*  # [linux and cuda_compiler_version == "None"]
    - setuptools_scm
    - numpy 1.19.*
    - scipy
    - dargs >=0.2.6
    - pyyaml
    - {{ mpi }}  # [linux]
    - python-hostlist >=1.21
    - h5py
    - wcmatch

  run:
    - python
    - tensorflow {{ tf_version }}.* cuda{{ cuda_compiler_version | replace('.', '') }}*  # [cuda_compiler_version != "None"]
    - tensorflow {{ tf_version }}.* cpu_*  # [cuda_compiler_version == "None"]
    - libtensorflow_cc {{ tf_version }}.* cuda{{ cuda_compiler_version | replace('.', '') }}*  # [linux and cuda_compiler_version != "None"]
    - libtensorflow_cc {{ tf_version }}.* cpu_*  # [linux and cuda_compiler_version == "None"]
    - numpy 1.19.*
    - scipy
    - dargs >=0.2.6
    - pyyaml
    - {{ mpi }}  # [linux]
    - python-hostlist >=1.21
    - h5py
    - wcmatch
    - lammps 2021.09.29  # [linux]

test:
  files:
    - water_se_a.json
  source_files:
    - examples/water/data
  imports:
    # dlopen: cannot load any more object with static TLS
    # because tensorflow link too many libraries
    # but it can successfully run on my machine
    - deepmd  # [not linux]
  #requires:
  #  - pip
  commands:
    #- pip check
    - dp -h  # [not linux]
    - dp train -h  # [not linux]
    - dp freeze -h  # [not linux]
    - dp test -h  # [not linux]
    - mv examples/water/data/data_0 ./data
    - dp train water_se_a.json  # [not linux]
    - dp freeze  # [not linux]

about:
  home: https://github.com/deepmodeling/deepmd-kit
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: A deep learning package for many-body potential energy representation and molecular dynamics
  doc_url: https://github.com/deepmodeling/deepmd-kit
  dev_url: https://github.com/deepmodeling/deepmd-kit

extra:
  recipe-maintainers:
    - njzjz
