{% set name = "deepmd-kit" %}
{% set version = "3.0.0rc0" %}
{% set lammps_version = "stable_29Aug2024" %}
{% set lammps_date = datetime.datetime.strptime(lammps_version.split('_')[1], "%d%b%Y") %}
{% set lammps_conda_version = "{:%Y.%m.%d}".format(lammps_date) %}
{% set proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/deepmodeling/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: e1b73fdfbc39fe8b20e6396826da6ba6d33c4e007513510a48aebc90efd5e972
  - url: https://github.com/lammps/lammps/archive/{{ lammps_version }}.tar.gz
    sha256: 6112e0cc352c3140a4874c7f74db3c0c8e30134024164509ecf3772b305fde2e
    folder: lammps

build:
  number: 0
  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ mpi_prefix }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ mpi_prefix }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  skip: true  # [win]
  skip: true  # [cuda_compiler_version in ("10.2", "11.0", "11.1")]
  skip: true  # [py<39]
  # https://github.com/conda-forge/tensorflow-feedstock/pull/367#issuecomment-1890751416
  skip: true  # [py==312 and cuda_compiler_version in ("11.2", "11.8")]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - cmake >=3.23
    - make  # [unix]
    - ninja
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ mpi }}  # [build_platform != target_platform and mpi == "openmpi"]

  host:
    - python
    - pip
    - scikit-build-core
    - hatch-fancy-pypi-readme
    - tensorflow  # [not (cuda_compiler_version or "").startswith("11")]
    # https://github.com/conda-forge/tensorflow-feedstock/pull/367#issuecomment-1890751416
    - tensorflow 2.14.*  # [(cuda_compiler_version or "").startswith("11")]
    - tensorflow * {{ proc_type }}*
    - pytorch  # [not (cuda_compiler_version or "").startswith("11")]
    - pytorch * {{ proc_type }}*
    - pytorch 2.0.*  # [(cuda_compiler_version or "").startswith("11")]
    - setuptools_scm
    - {{ mpi }}
    - cub  # [cuda_compiler_version == '10.2']
    - cuda-cudart-dev  # [(cuda_compiler_version or "").startswith("12")]
    - cuda-version {{ cuda_compiler_version }}  # [(cuda_compiler_version or "").startswith("12")]
    # require by pytorch
    - libcublas-dev    # [(cuda_compiler_version or "").startswith("12")]
    - libcurand-dev  # [(cuda_compiler_version or "").startswith("12")]
    - libcufft-dev     # [(cuda_compiler_version or "").startswith("12")]
    - cuda-nvrtc-dev   # [(cuda_compiler_version or "").startswith("12")]
    - cuda-nvtx-dev    # [(cuda_compiler_version or "").startswith("12")]

  run:
    - python
    - tensorflow
    - tensorflow * {{ proc_type }}*
    - pytorch
    - pytorch * {{ proc_type }}*
    - numpy >=1.21
    - scipy
    - dargs >=0.4.7
    - pyyaml
    - {{ mpi }}
    - h5py
    - wcmatch
    - packaging
    - ml_dtypes
    - mendeleev
    - array-api-compat
    # jax
    - jax >=0.4.33  # [py>=310 and not (cuda_compiler_version or "").startswith("11")]
    - jaxlib * {{ proc_type }}*  # [py>=310 and not (cuda_compiler_version or "").startswith("11")]
    - flax >=0.10.0  # [py>=310 and not (cuda_compiler_version or "").startswith("11")]
    - orbax-checkpoint  # [py>=310 and not (cuda_compiler_version or "").startswith("11")]

  run_constrained:
    - lammps {{ lammps_conda_version }} *_{{ mpi_prefix }}_*

test:
  files:
    - water_se_a.json
    - water.lmp
    - in.lammps
  source_files:
    - examples/water/data
  imports:
    - deepmd
    - deepmd.tf
    - deepmd.pt
    - deepmd.jax  # [py>=310]
  requires:
    - pip
    - lammps
  commands:
    - pip check
    - dp -h
    - dp train -h
    - dp freeze -h
    - dp test -h
    - mv examples/water/data/data_0 ./data
    - dp train water_se_a.json
    - dp freeze -o frozen_model.pb
    - export OMPI_MCA_plm=isolated OMPI_MCA_btl_vader_single_copy_mechanism=none OMPI_MCA_rmaps_base_oversubscribe=yes OMPI_MCA_plm_ssh_agent=false  # [mpi == "openmpi"]
    - mpiexec -n 1 lmp_mpi -in in.lammps

about:
  home: https://github.com/deepmodeling/deepmd-kit
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: A deep learning package for many-body potential energy representation and molecular dynamics
  doc_url: https://github.com/deepmodeling/deepmd-kit
  dev_url: https://github.com/deepmodeling/deepmd-kit

extra:
  recipe-maintainers:
    - njzjz
